sql
llwh2333/TG-informer pull request #13
Opened 2023-06-02 07:01 UTC by monkeyh0ck

2023-06-02 07:04 UTC, monkeyh0ck commented
实现用户信息、频道信息、消息信息写入数据库
存在两个问题：
## informer.py中  363  行  messqge_info两项存在问题 
1. 'mentioned_user': None,             返回的数据类型是str，数据库的数据类型是BigInteger
2. 'message_channel_size':0            需要实现根据channel_id获取群组用户数据

2023-06-02 08:09 UTC, monkeyh0ck commented
群组的用户信息目前还是只抓200个，没有解决请求太多被ban

2023-06-04 08:27 UTC, llwh2333 requested changes
fwd_message_txt 是多余的不用添加
mentioned_user 这为什么要改成none
其它两个部分（message、channel）的先不提交
informer.py 文件的 base 版本不对，需要更新到现在的，再提交 merge

2023-06-04 09:26 UTC, monkeyh0ck commented
1.数据库存在fwd_message_txt 字段，我就根据reply_message_txt加上了
2.get_message_info_from_event函数返回的mentioned_user字段存在问题，数据库字段类型是BigInteger，函数返回字段是数组，数组里的数据是str，例如：@llwh2333
3.数据库添加内容方法一样，我就都加上了，目前除了get_message_info_from_event返回的数据存在问题，导致写入sql时报错，部分返回字段一场会报错但不会影响程序执行
4.我直接fork的，版本应该是一致的
5.message_channel_size返回的数据存在问题，无法直接使用，需要重新设计。目前暂定为0
6.针对第三条，message写入数据库时部分字段报错，需要大家一起测试，找出报错字段，然后进行修改

2023-06-04 12:46 UTC, llwh2333 requested changes
fwd_message_txt 是需要删掉的，因为它是指转发的消息的内容
关于 mentioned_user 最后发现能获得的只有 user name 所以不需要 mentioned_user_id 这些
sql moudle 的那个文件是原本的 project 写的，有些东西我们不需要，也有些是我以前写的，实际上获取不到，所以你可以根据情况修改，而且之前根据 get_message_info_from_event 能正常获取，并 dump 为 json 文件，所以程序能正常运行一般就说明不是这个函数的问题
你 fork 后，后面又有更新的内容，但你的 fork 没有更新，所以和 test 的版本并不一定一样

2023-06-04 13:35 UTC, closed without merging